remove trailing slashes from api urls and return empty list when there are no users
aws-samples/aws-serverless-saas-workshop pull request #50
Opened 2022-12-05 15:22 UTC by shannoncolavita

*Issue #, if available:*

*Description of changes:*
1. Removed trailing slashes from api urls as this results in urls with double slashes, sometimes resulting in CORS issues.
2. Return empty list when there are no users as this results in API Gateway error as null was being returned 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-08 16:55 UTC, ujwalbukka commented on Lab1/scripts/deployment.sh
> +  APP_APIGATEWAYURL=${APP_APIGATEWAYURL%/}
Actually in the Cloudformation template, output value of these api gateway url output parameters have a trailing slash appended. I think we should remove the trailing slash for those output parameters in the cloudformation templates. You need to update server/shared-template.yaml and server/tenant-template.yaml files in each lab.

2022-12-08 16:58 UTC, ujwalbukka commented on Lab2/server/TenantManagementService/user-management.py
> +
Good catch. Thanks. Will be waiting on above fix to merge everything.

2022-12-08 16:59 UTC, ujwalbukka requested changes
Please review the comments and do the needful. Thanks.

2022-12-09 11:28 UTC, shannoncolavita commented
Please review again when you get a chance, have removed the trailing slashes from the sam templates

2022-12-16 15:13 UTC, shannoncolavita commented
@ujwalbukka Please review again when you get a chance, have removed the trailing slashes from the sam templates and reverted the changes to the deployment.sh files, thanks!

2022-12-20 15:15 UTC, ujwalbukka approved these changes

2022-12-20 15:16 UTC, merged